### PR TITLE
WIP: Mediachain examples

### PR DESCRIPTION
**Pull request by parkan**
Opening this for discussion. Right now the example objects are basically schema.org CreativeWork types, extensions to be added

cc @yusefnapora

### CODE REVIEW

**Comment by jbenet** [comment]
Awesome, thank you

**Comment by parkan** [comment]
@jbenet: one thing that's unclear to me is object type descriptors. Will there be something native in the format that tells me this object is a `unixfs` structure vs `mediachain` structure, either in the header or as a toplevel namespace/context type element? I haven't seen this in any of the examples yet, the type is always specified in a comment

**Comment by jbenet** [comment]
@parkan we could use `@type` for this, though it may be used for JSON-LD already. In general, if something bears a JSON-LD type then that likely should be enough.

**Comment by jbenet** [comment]
in general, i'm all for supporting type systems. would be nice to have a proper global type system,

---

(compat note: if we use `@` for `@link`, we need to escape `@`, which would make JSON-LD's `@type` be stored as `\@type` right @mildred ?)

**Comment by mildred** [comment]
Not necessarily. The escaping is necessary if the IPLD paths are to be the same as the unixfs paths. If we lift this restriction, I don't think we need escaping.

Some other uses might want to do escaping, that could be the case for JSON-LD if it also defined a `@link` keyword. But as [it is not the case](https://www.w3.org/TR/json-ld/#dfn-keyword) I think it is safe to use `@link` internally. And I don't think JSON-LD prevents documents from having keys starting with the `@` character (someone more knowledgeable than me on JSON-LD syntax could comment on this).

**Comment by mildred** [comment]
If we want to be compatible with JSON-LD, I would recommend to follow its recommendation. Types are introduced using the `@context` keyword, and the context itself must follow JSON-LD syntax.

The `@type` keyword a spacial. It is used inside contexts to define the type of simple values (as opposed to the type of compound objects, that's the context). Outside the context, `@type` is used in conjunction with `@value` to define a simple typed value.

By simple value, I mean something like strings, typed strings, integers, booleans. Compound objects are things like array, maps, JSON objects, structs, ...

**Comment by jbenet** [comment]
Thanks for the reminders @mildred! 

If we do not do escaping ourselves (yay!) we should direct users to escape leading `@` thesmelves if they don't intend IPFS to use them (i.e. they have their own `@link`).

**Comment by parkan** [comment]
@mildred my understanding was that `@context` in itself does not convey type information, only the prefixes added to short-hand names. On the other hand, `@type` can convey type information both for a bare value _and_ a node (i.e. object) as shown [here](https://www.w3.org/TR/json-ld/#dfn-node-type)

If you look at the examples given at schema.org, they will specify both `@context` for prefixes and `@type`, e.g. http://schema.org/MusicRecording

```
{
    "@context": "http://schema.org",
    "@type": "MusicRecording",
    "@id": "http://musicbrainz.org/recording/3566e453-8f10-4a45-ac85-2c72eb183ca1",
    "name": "Back in the U.S.S.R.",
    "producer": {
        "@type": "Person",
        "name": "George Martin"
    },
    "duration": "PT2M43S",
    "recordingOf": {
        "@type": "MusicComposition",
        "name": "Back in the U.S.S.R",
        "iswcCode": "T-010.140.236-1"
    }
}
```

Maybe I misunderstood what you meant by

> It is used inside contexts to define the type of simple values (as opposed to the type of compound objects, that's the context). 

?

**Comment by mildred** [comment]
You're right on this. I forgot the use of `@type` for nodes. However, I don't understand why the URL in `@context` doesn't link to a proper JSON-LD context.

I re-read again the specification and I understood that `@type` is meant to identify the type of object defined in the JSON-LD, however, the `@context` defines how it is represented: which key names are used for what object properties. It represents the actual format.

If you transform the JSON-LD document to an XML RDF document, the `@context` would disappear because it is specific to the encoding in JSON, but the `@type` information would be left as the represented object is the same.

**Comment by mildred** [comment]
> If we do not do escaping ourselves (yay!) we should direct users to escape leading @ thesmelves if they don't intend IPFS to use them (i.e. they have their own @link).

There are multiple cases:
- Pure JSON-LD documents would not use IPLD `@link` property and won't have a problem.
- Mixed JSON-LD ∕ IPLD documents would have the `@link` property: just fetch the document recursively and replace the links by the actual sub-documents, and you have a document without `@link`s
- Or if only a part of the document is needed, the `@link` properties can be removed prior to feeding it to the JSON-LD parser. Or use a parser that won't trigger an error on `@link` properties.

It would be nice to try it out, but I believe JSON-LD parsers won't have a problem with `@link` keys. The might just as well ignore them. That's just what we want them to do in that case.

**Comment by parkan** [comment]
@mildred 

I think  you can specify term types by _either_ in `@context` _or_ on the value object itself:

```
{
  "@context":
  {
    "modified":
    {
      "@id": "http://purl.org/dc/terms/modified",
      "@type": "http://www.w3.org/2001/XMLSchema#dateTime"
    }
  },
...
  "@id": "http://example.com/docs/1",
  "modified": "2010-05-29T14:17:39+02:00",
...
}
```

```
{
  "@context":
  {
    "modified":
    {
      "@id": "http://purl.org/dc/terms/modified"
    }
  },
...
  "modified":
  {
    "@value": "2010-05-29T14:17:39+02:00",
    "@type": "http://www.w3.org/2001/XMLSchema#dateTime"
  }
...
}
```

(from https://www.w3.org/TR/json-ld/#typed-values)

so the type of `producer` above could also have been specified this way

```
"@context": {
  "producer": {
    "@type": "Person"
  }
},
"producer": {
  "name" : "George Martin"
}
```

but you're right, I don't really understand the handling of `@context` as prefix in this case. It **does** validate and expands to the following:

```
[
  {
    "@id": "http://musicbrainz.org/recording/3566e453-8f10-4a45-ac85-2c72eb183ca1",
    "@type": [
      "http://schema.org/MusicRecording"
    ],
    "http://schema.org/duration": [
      {
        "@value": "PT2M43S"
      }
    ],
    "http://schema.org/name": [
      {
        "@value": "Back in the U.S.S.R."
      }
    ],
    "http://schema.org/producer": [
      {
        "@type": [
          "http://schema.org/Person"
        ],
        "http://schema.org/name": [
          {
            "@value": "George Martin"
          }
        ]
      }
    ],
    "http://schema.org/recordingOf": [
      {
        "@type": [
          "http://schema.org/MusicComposition"
        ],
        "http://schema.org/iswcCode": [
          {
            "@value": "T-010.140.236-1"
          }
        ],
        "http://schema.org/name": [
          {
            "@value": "Back in the U.S.S.R"
          }
        ]
      }
    ]
  }
]
```

The spec does allow for relative urls (implicitly or through `@base`) but those look like normal json-ld documents too. Hmm.

**Pull request merged**
